#!/usr/bin/env python

import os
import runpy
import sys

ME = 'termitheme'
PKG = 'termitheme_lib'

major, minor, micro, level, serial = sys.version_info
if major > 2:
    raise Exception("This version of %s does not run under Python 3.x" % ME)
if major < 2 or minor < 5 or (minor == 5 and level < "candidate"):
    raise Exception("This version of %s requires Python 2 >= 2.5.0" % ME)

try:
    run_globals = runpy.run_module(PKG, run_name='__main__', alter_sys=True)
    executed = os.path.splitext(os.path.basename(run_globals['__file__']))[0]
    if executed != '__main__': # For Python 2.5 compatibility
        raise ImportError('Incorrectly executed %s instead of __main__' %
                          executed)
except ImportError: # For Python 2.6 compatibility
    runpy.run_module('%s.__main__' % PKG, run_name='__main__', alter_sys=True)
